# Generated by Django 4.1.6 on 2023-02-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
