# Generated by Django 4.1.6 on 2023-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
