# Generated by Django 4.1.6 on 2023-02-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
